In [13]:
import os, glob
import pandas as pd

Load data from every file with **Mutect2** results and add it to `mutect_df`:

In [50]:
os.chdir("../../body/1raw/MtMutectAnnovar/")

mutect_df = pd.DataFrame(
    columns=['CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO', 'FORMAT', 'SAMPLE_ID', 'filename'])

for file in glob.glob("*mutect.mt"):
    df = pd.read_csv(file, sep='\t', header=None,  comment='#')
    df.columns = ['CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO', 'FORMAT', 'SAMPLE_ID']
    sample = file.split(".")[0]
    df['filename'] = sample
    mutect_df = mutect_df.append(df)

In [64]:
print(mutect_df.shape[0], 'lines')
mutect_df.head()

59989 lines

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,SAMPLE_ID,filename
0,MT,73,.,A,G,.,.,"DP=583;ECNT=2;MBQ=0,41;MFRL=0,15928;MMQ=60,60;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,572:0.998:572:0,274:0,282:0,0,242,330",19847_4#6
1,MT,152,.,T,C,.,.,"DP=1073;ECNT=2;MBQ=0,41;MFRL=0,15901;MMQ=60,60...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,1056:0.999:1056:0,496:0,541:0,0,489,567",19847_4#6
2,MT,263,.,A,G,.,.,"DP=611;ECNT=3;MBQ=37,41;MFRL=497,582;MMQ=60,60...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:1,590:0.997:591:1,286:0,274:1,0,224,366",19847_4#6
3,MT,302,.,A,C,.,.,"DP=478;ECNT=3;MBQ=22,8;MFRL=513,445;MMQ=60,60;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:424,24:0.015:448:109,0:129,4:109,315,1,23",19847_4#6
4,MT,310,.,T,"TC,C",.,.,"DP=467;ECNT=3;MBQ=0,27,12;MFRL=0,15896,453;MMQ...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:0,346,76:0.837,0.161:422:0,84,7:0,154,6:...",19847_4#6

Load the table with mapped info:

In [65]:
info_df = pd.read_csv("../treatment_mapped_to_kostya_files.csv", index_col=0)
print(info_df.shape[0], 'lines')
info_df.head()

2441 lines

,kostya_file,filename,size,accession,sample,subsample,treatment
0,EGAF00002339775/22156_8#16.cram,22156_8#16,1.7G,EGAN00001938950,MSM0.105,s3,Acetaldehyde (12 mM)
1,EGAF00002339256/22210_2#12.cram,22210_2#12,1.4G,EGAN00001437534,MSM0.68,s3,DMS (0.078 mM)
2,EGAF00002339954/22101_4#5.cram,22101_4#5,1.8G,EGAN00001938961,MSM0.101,s1,Cyclophosphamide (60 uM) + S9
3,EGAF00002339160/21898_6.cram,21898_6,33G,EGAN00001938938,MSM0.126,s2,4-ABP (300 uM) + S9
4,EGAF00002338479/23627_5#1.cram,23627_5#1,5.9G,EGAN00001939019,SIGmut6993676,-,NaN

Merge the two tables into one `grand_df`:

In [66]:
grand_df = pd.merge(mutect_df, info_df, how='outer', on='filename')
print(grand_df.shape[0], 'lines')
grand_df.head()

61064 lines

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,SAMPLE_ID,filename,kostya_file,size,accession,sample,subsample,treatment
0,MT,73,.,A,G,.,.,"DP=583;ECNT=2;MBQ=0,41;MFRL=0,15928;MMQ=60,60;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,572:0.998:572:0,274:0,282:0,0,242,330",19847_4#6,EGAF00002338644/19847_4#6.cram,4.6G,EGAN00001437483,MSM0.46,s1,Cobalt (II) chloride (250 uM)
1,MT,152,.,T,C,.,.,"DP=1073;ECNT=2;MBQ=0,41;MFRL=0,15901;MMQ=60,60...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:0,1056:0.999:1056:0,496:0,541:0,0,489,567",19847_4#6,EGAF00002338644/19847_4#6.cram,4.6G,EGAN00001437483,MSM0.46,s1,Cobalt (II) chloride (250 uM)
2,MT,263,.,A,G,.,.,"DP=611;ECNT=3;MBQ=37,41;MFRL=497,582;MMQ=60,60...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:1,590:0.997:591:1,286:0,274:1,0,224,366",19847_4#6,EGAF00002338644/19847_4#6.cram,4.6G,EGAN00001437483,MSM0.46,s1,Cobalt (II) chloride (250 uM)
3,MT,302,.,A,C,.,.,"DP=478;ECNT=3;MBQ=22,8;MFRL=513,445;MMQ=60,60;...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1:424,24:0.015:448:109,0:129,4:109,315,1,23",19847_4#6,EGAF00002338644/19847_4#6.cram,4.6G,EGAN00001437483,MSM0.46,s1,Cobalt (II) chloride (250 uM)
4,MT,310,.,T,"TC,C",.,.,"DP=467;ECNT=3;MBQ=0,27,12;MFRL=0,15896,453;MMQ...",GT:AD:AF:DP:F1R2:F2R1:SB,"0/1/2:0,346,76:0.837,0.161:422:0,84,7:0,154,6:...",19847_4#6,EGAF00002338644/19847_4#6.cram,4.6G,EGAN00001437483,MSM0.46,s1,Cobalt (II) chloride (250 uM)

Save the table to a `.csv` file:

In [68]:
grand_df.to_csv("../../2derived/mutations_vs_treatment.csv")